"""
@file plot_length_dist.py
@brief Generates a bar chart for word length distribution.

This script reads the CSV file generated by the C++ analyzer
containing the word length distribution and produces a bar chart
showing the frequency of each word length.

The resulting plot is saved in the output directory.

@see plot_utils.save_figure
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
from plot_utils import save_figure

output_dir = 'output'
filename = 'length_dist.csv'
plot_name = 'length_distribution.png'

def main():
    """
    @brief Main entry point for the word length distribution plot.

    Reads the CSV file containing word lengths and frequencies,
    sorts the data by word length, and generates a bar chart.

    @return None
    """
    df = pd.read_csv(os.path.join(output_dir, filename))
    df = df.sort_values('length')

    plt.bar(
        df['length'],
        df['frequency']
    )

    plt.xlabel('Word length')
    plt.ylabel('Frequency')
    plt.title('Word Length Distribution')
    plt.grid(axis='y')

    save_figure(output_dir,plot_name)

if __name__=='__main__':
    main()