"""
@file plot_sort_metrics.py
@brief Plots sorting algorithm performance metrics.

This script reads the CSV file containing sorting benchmark results
generated by the C++ analyzer and plots execution time, comparisons, 
and swaps as a function of input size n for different algorithms and 
ordering criteria.

The resulting line charts allow direct comparison between MergeSort 
and QuickSort under alphabetical and frequency-based ordering.

@see plot_utils.save_figure
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
from plot_utils import save_figure

output_dir = 'output'
filename = 'sort_metrics.csv'

def plot_metric(df: pd.DataFrame, metric: str, plot_name: str):
    """
    @brief Plots a specific sorting performance metric.

    This function generates a line plot of the selected metric (e.g., 
    execution time, comparisons, or swaps) as a function of input size 
    for each algorithm and ordering type.

    @param df DataFrame containing the sorting benchmark data.
    @param metric The metric to plot ('time_s', 'comparisons', 'swaps').
    @param plot_name The name of the file to save the plot.

    @return None
    """
    for label, group in df.groupby('label'):
        group = group.sort_values('n')

        plt.plot(
            group['n'],
            group[metric],
            marker='o',
            label=label
        )
    
    plt.title(f'{metric.capitalize()} vs Input Size')
    plt.xlabel('Input size (n)')
    plt.ylabel(f'{metric.capitalize()}')
    plt.legend()
    plt.grid(True)
    
    save_figure(output_dir,plot_name)

def main():
    """
    @brief Main entry point for sorting performance plots.

    Reads sorting benchmark data from CSV, groups results by algorithm 
    and ordering type, and generates line plots for execution time, 
    comparisons, and swaps as a function of input size.

    @return None
    """
    df = pd.read_csv(os.path.join(output_dir, filename))

    df['label'] = df['algorithm'] + ' - ' + df['order']

    plot_metric(df, 'time_s', 'sort_performance_time.png')
    plot_metric(df, 'comparisons', 'sort_performance_comparisons.png')
    plot_metric(df, 'swaps', 'sort_performance_swaps.png')



if __name__ == '__main__':
    main()