"""
@file plot_sort_metrics.py
@brief Plots sorting algorithm performance metrics.

This script reads the CSV file containing sorting benchmark results
generated by the C++ analyzer and plots execution time T(n) as a
function of input size n for different algorithms and ordering
criteria.

The resulting line chart allows direct comparison between
MergeSort and QuickSort under alphabetical and frequency-based
ordering.

@see plot_utils.save_figure
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
from plot_utils import save_figure

output_dir = 'output'
filename = 'sort_metrics.csv'
plot_name = 'sort_performance.png'

def main():
    """
    @brief Main entry point for sorting performance plots.

    Reads sorting benchmark data from CSV, groups results by
    algorithm and ordering type, and generates a line plot of
    execution time versus input size.

    @return None
    """
    df = pd.read_csv(os.path.join(output_dir, filename))

    df['label'] = df['algorithm'] + ' - ' + df['order']

    for label, group in df.groupby('label'):
        group = group.sort_values('n')

        plt.plot(
            group['n'],
            group['time_s'],
            marker='o',
            label=label
        )
    
    plt.title(f'Sorting Performance')
    plt.xlabel('Input size (n)')
    plt.ylabel('Time (s)')
    plt.legend()
    plt.grid(True)
    
    save_figure(output_dir,plot_name)

if __name__ == '__main__':
    main()